# docker-compose.yml
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/speech_therapy
      - SECRET_KEY=your-secret-key-here
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - db
    networks:
      - speech-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=speech_therapy
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - speech-network

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - speech-network

volumes:
  mysql-data:

networks:
  speech-network:
    driver: bridge